import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-bootstrap";
import { BsChevronLeft, BsChevronRight } from "react-icons/bs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main style={{ width: "60%", margin: "auto", paddingTop: "10px" }}>
        <Carousel
          interval={null}
          nextLabel={
            <span
              style={{ color: "red", fontWeight: "bold", fontSize: "30px" }}
            >
              Next
            </span>
          }
          nextIcon={<BsChevronRight color="red" size={50} />}
          prevIcon={<BsChevronLeft color="green" size={50} />}
          prevLabel={
            <span
              style={{ color: "green", fontWeight: "bold", fontSize: "30px" }}
            >
              Previous
            </span>
          }
        >
          {Array.from({ length: 50 }).map((_, index) => (
            <Carousel.Item>
              <Image
                src={`/images/${index + 1}.png`}
                alt="First slide"
                height={500}
                width={1200}
              />
              <Carousel.Caption>
                <h3 style={{ color: "red" }}>
                  <span style={{ color: "green" }}>Slide No.</span> {index + 1}
                </h3>
              </Carousel.Caption>
            </Carousel.Item>
          ))}
        </Carousel>
      </main>
    </>
  );
}
