// import Head from "next/head";
// import Image from "next/image";
// import { Carousel } from "react-bootstrap";
// import { BsChevronLeft, BsChevronRight } from "react-icons/bs";

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//         <link
//           rel="stylesheet"
//           href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
//           integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
//           crossOrigin="anonymous"
//           referrerPolicy="no-referrer"
//         />
//       </Head>
//       <main style={{ width: "60%", margin: "auto", paddingTop: "10px" }}>
//         <Carousel
//           interval={null}
//           nextLabel={
//             <span
//               style={{ color: "red", fontWeight: "bold", fontSize: "30px" }}
//             >
//               Next
//             </span>
//           }
//           nextIcon={<BsChevronRight color="red" size={50} />}
//           prevIcon={<BsChevronLeft color="green" size={50} />}
//           prevLabel={
//             <span
//               style={{ color: "green", fontWeight: "bold", fontSize: "30px" }}
//             >
//               Previous
//             </span>
//           }
//         >
//           {Array.from({ length: 50 }).map((_, index) => (
//             <Carousel.Item key={index}>
//               <div className="image-container">
//                 <Image
//                   src={`/images/${index + 1}.png`}
//                   alt="First slide"
//                   height={500}
//                   width={1300}
//                   className="carousel-image"
//                   priority={true}
//                 />
//               </div>
//               <Carousel.Caption>
//                 <h3 style={{ color: "red" }}>
//                   <span style={{ color: "green" }}>Slide No.</span> {index + 1}
//                 </h3>
//               </Carousel.Caption>
//             </Carousel.Item>
//           ))}
//         </Carousel>
//       </main>
//     </>
//   );
// }

import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-bootstrap";
import { BsChevronLeft, BsChevronRight } from "react-icons/bs";

export default function Home() {
  const [currentSlide, setCurrentSlide] = useState(0);

  const handleSlideChange = (slideIndex) => {
    setCurrentSlide(slideIndex);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main style={{ width: "60%", margin: "auto", paddingTop: "10px" }}>
        <Carousel
          interval={null}
          nextLabel={
            <span
              style={{ color: "red", fontWeight: "bold", fontSize: "30px" }}
            >
              Next
            </span>
          }
          nextIcon={<BsChevronRight color="red" size={50} />}
          prevIcon={<BsChevronLeft color="green" size={50} />}
          prevLabel={
            <span
              style={{ color: "green", fontWeight: "bold", fontSize: "30px" }}
            >
              Previous
            </span>
          }
          activeIndex={currentSlide}
          onSelect={handleSlideChange}
        >
          {Array.from({ length: 50 }).map((_, index) => {
            const shouldPreload =
              Math.abs(index - currentSlide) <= 2 ||
              index === 1 ||
              index === 49;
            return (
              <Carousel.Item key={index}>
                <div className="image-container">
                  <Image
                    src={`/images/${index + 1}.png`}
                    alt={`Slide ${index + 1}`}
                    height={500}
                    width={1300}
                    className="carousel-image"
                    priority={shouldPreload}
                  />
                </div>
                <Carousel.Caption>
                  <h3 style={{ color: "red" }}>
                    <span style={{ color: "green" }}>Slide No.</span>{" "}
                    {index + 1}
                  </h3>
                </Carousel.Caption>
              </Carousel.Item>
            );
          })}
        </Carousel>
      </main>
    </>
  );
}
